spring.application.name=student-planner
server.port=${PORT:8080}
spring.data.mongodb.uri=${MONGODB_URI:}
spring.data.mongodb.database=${MONGODB_DATABASE:student-planner}
spring.data.mongodb.auto-index-creation=true
